name: Daily Job

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
      SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
      DISCOVER_WEEKLY_PLAYLIST_ID: ${{ secrets.DISCOVER_WEEKLY_PLAYLIST_ID }}
      DAILY_DRIVE_PLAYLIST_ID: ${{ secrets.DAILY_DRIVE_PLAYLIST_ID }}
      SPOTICRON_PLAYLIST_ID: ${{ secrets.SPOTICRON_PLAYLIST_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Run script
      run: python spoticron/job.py
